### ISSUE TITLE
Erie Crash Report

### ISSUE THREAD

**Issue by ddanielvega** [festivaldev/festivaldev.github.io#1]
- Erie makes my iPhone 6s on 10.2 crash into safe mode mostly when 3D touching an App and when I invoque the App Switcher via 3D Touch gesture.
- Crashlog:

[Erie Cash.pdf](https://github.com/festivaldev/festivaldev.github.io/files/1229673/Erie.Cash.pdf)

**Comment by vainamov** [comment]
This is not the Redstone repo! Please refer to [Redstone/Issues](https://github.com/festivaldev/Redstone/issues/).

**Comment by ddanielvega** [comment]
What are you talking about? This guy clearly says we can open the issues right on this link.

[image1.JPG]

– Daniel

Sent from my iPhone

El 17/08/2017, a las 2:58 a.m., Väinämö Łūmikērø <notifications@github.com<mailto:notifications@github.com>> escribió:


This is not the Redstone repo! Please refer to Redstone/Issues<https://github.com/festivaldev/Redstone/issues/>.

**Comment by SniperGER** [comment]
Nothing to worry about. Just a plain and simple misunderstanding.

**Comment by SniperGER** [comment]
Also it doesn't look like Erie is causing the crash, neither is any other tweak.

**Comment by ddanielvega** [comment]
It happened after installing Erie, as I don't see interest I'm uninstalling it right away, thank you.

– Daniel

Sent from my iPhone

El 17/08/2017, a las 2:12 p.m., Janik Schmidt <notifications@github.com<mailto:notifications@github.com>> escribió:


Also it doesn't look like Erie is causing the crash, neither is any other tweak.
